import './globals.css'
import { Roboto } from 'next/font/google'
const roboto = Roboto({ subsets: ['latin'], weight: [
  '300',
  '500',
  '700',
  '900'
] })

export const metadata = {
  title: 'Universo',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className={`${roboto.className} max-w-[1440px] m-auto`}>
        {children}
        </body>
    </html>
  )
}
